#!/usr/bin/env python3
"""Build data/tonies.json and TONIES.md from data/tonies/**/*.nfc.

Stdlib only. Run from anywhere; paths are resolved relative to the repo root
(the parent of this script's directory).
"""

from __future__ import annotations

import json
import sys
import urllib.parse
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from tonie_writer.nfcfile import NfcParseError, parse_nfc_file  # noqa: E402
from tonie_writer.normalize import build_haystack, slugify  # noqa: E402

TONIES_DIR = REPO_ROOT / "data" / "tonies"
TONIES_JSON = REPO_ROOT / "data" / "tonies.json"
UPSTREAM_JSON = REPO_ROOT / "data" / "UPSTREAM.json"
TONIES_MD = REPO_ROOT / "TONIES.md"


def collect_entries(tonies_dir: Path) -> list[dict]:
    entries = []
    seen_ids: dict[str, int] = {}

    for nfc_path in sorted(tonies_dir.rglob("*.nfc")):
        rel = nfc_path.relative_to(tonies_dir)
        parts = rel.parts
        if len(parts) < 2:
            print(f"warning: {nfc_path}: not nested under a language directory, skipping", file=sys.stderr)
            continue

        language = parts[0]
        series_parts = list(parts[1:-1])
        name = nfc_path.stem

        try:
            tag = parse_nfc_file(nfc_path)
        except NfcParseError as exc:
            print(f"warning: {nfc_path}: {exc}", file=sys.stderr)
            continue

        series = "/".join(series_parts)

        slug_parts = [slugify(language)] + [slugify(p) for p in series_parts] + [slugify(name)]
        base_id = "/".join(p for p in slug_parts if p)
        entry_id = base_id
        if base_id in seen_ids:
            seen_ids[base_id] += 1
            entry_id = f"{base_id}-{seen_ids[base_id]}"
        else:
            seen_ids[base_id] = 1

        entries.append(
            {
                "id": entry_id,
                "name": name,
                "series": series,
                "language": language,
                "path": str((TONIES_DIR / rel).relative_to(REPO_ROOT)).replace("\\", "/"),
                "uid": tag.uid,
                "search": build_haystack(language, series, name),
            }
        )

    entries.sort(key=lambda e: (e["language"], e["series"], e["name"]))
    return entries


def load_upstream_commit() -> str:
    if not UPSTREAM_JSON.exists():
        return "unknown"
    try:
        data = json.loads(UPSTREAM_JSON.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return "unknown"
    commit = data.get("commit", "unknown")
    return commit[:7] if commit != "unknown" else commit


def build_tonies_json_payload(entries: list[dict], upstream_commit: str) -> dict:
    return {
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "upstream_commit": upstream_commit,
        "count": len(entries),
        "tonies": entries,
    }


def write_tonies_json(entries: list[dict]) -> None:
    payload = build_tonies_json_payload(entries, load_upstream_commit())
    with TONIES_JSON.open("w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, ensure_ascii=False)
        f.write("\n")


def find_duplicate_uids(entries: list[dict]) -> dict[str, list[dict]]:
    by_uid: dict[str, list[dict]] = defaultdict(list)
    for entry in entries:
        by_uid[entry["uid"]].append(entry)
    return {uid: group for uid, group in by_uid.items() if len(group) > 1}


def encode_path(path: str) -> str:
    return "/".join(urllib.parse.quote(segment) for segment in path.split("/"))


def format_uid(uid: str) -> str:
    return " ".join(uid[i : i + 2] for i in range(0, len(uid), 2))


def render_tonies_md(
    entries: list[dict],
    upstream_commit: str,
    synced_at: str,
    upstream_repo: str = "https://github.com/nortakales/flipper-zero-tonies",
) -> str:
    lines: list[str] = []
    lines.append("# Available Tonies")
    lines.append("")
    lines.append("*This file is generated by `scripts/build_index.py` — do not edit manually.*")
    lines.append("")
    lines.append(
        f"Upstream: [nortakales/flipper-zero-tonies]({upstream_repo}) @ `{upstream_commit}` "
        f"· synced {synced_at} · **{len(entries)} Tonies**"
    )
    lines.append("")
    lines.append('How to write one of these to a tag: `./tonie write "<name>"`')
    lines.append("")

    by_language: dict[str, list[dict]] = defaultdict(list)
    for entry in entries:
        by_language[entry["language"]].append(entry)

    lines.append("| Language | Count |")
    lines.append("|---|---|")
    for language in sorted(by_language):
        lines.append(f"| {language} | {len(by_language[language])} |")
    lines.append("")

    for language in sorted(by_language):
        lines.append(f"## {language}")
        lines.append("")

        by_series: dict[str, list[dict]] = defaultdict(list)
        for entry in by_language[language]:
            by_series[entry["series"]].append(entry)

        for series in sorted(by_series, key=str.casefold):
            heading = series if series else "(uncategorized)"
            lines.append(f"### {heading}")
            lines.append("")
            lines.append("| Tonie | UID | File |")
            lines.append("|---|---|---|")
            for entry in sorted(by_series[series], key=lambda e: e["name"]):
                uid_display = format_uid(entry["uid"])
                link = encode_path(entry["path"])
                lines.append(f"| {entry['name']} | `{uid_display}` | [.nfc]({link}) |")
            lines.append("")

    duplicates = find_duplicate_uids(entries)
    if duplicates:
        lines.append("## Duplicate UIDs")
        lines.append("")
        lines.append(
            "Informational only — these files share a UID with at least one other "
            "entry and will overwrite one another when written."
        )
        lines.append("")
        for uid in sorted(duplicates):
            group = duplicates[uid]
            lines.append(f"### `{format_uid(uid)}`")
            lines.append("")
            for entry in group:
                lines.append(f"- {entry['language']} / {entry['series']} / {entry['name']}")
            lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def write_tonies_md(entries: list[dict]) -> None:
    upstream_commit = load_upstream_commit()
    synced_at = "unknown"
    if UPSTREAM_JSON.exists():
        try:
            synced_at = json.loads(UPSTREAM_JSON.read_text(encoding="utf-8")).get("synced_at", "unknown")
        except (json.JSONDecodeError, OSError):
            pass
    TONIES_MD.write_text(render_tonies_md(entries, upstream_commit, synced_at), encoding="utf-8")


def main() -> int:
    if not TONIES_DIR.exists():
        print(f"error: {TONIES_DIR} does not exist", file=sys.stderr)
        return 1

    entries = collect_entries(TONIES_DIR)

    if not entries:
        print(f"error: no valid .nfc files found under {TONIES_DIR}", file=sys.stderr)
        return 1

    write_tonies_json(entries)
    write_tonies_md(entries)
    print(f"Indexed {len(entries)} Tonies -> {TONIES_JSON.relative_to(REPO_ROOT)}, {TONIES_MD.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
